spring.application.name=cert-manager

spring.datasource.url=jdbc:mysql://localhost:3306/cert_manager
cert_manager
spring.datasource.username=Seu Usuario :)
spring.datasource.password=Sua senha   :)
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect